# Generated by Django 4.2.4 on 2023-08-20 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "managed": settings.IS_TESTING,
            },
        ),
    ]
